PTSL.GENERIC.Web.Core/Controllers/Project/BugAndDefectController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PTSL.eCommerce.Web.Core.Services.Interface.Project;
using PTSL.GENERIC.Web.Core.Helper;
using PTSL.GENERIC.Web.Core.Helper.Enum;
using PTSL.GENERIC.Web.Core.Model.EntityViewModels.Bugzilla;
using PTSL.GENERIC.Web.Core.Model.EntityViewModels.Project;
using PTSL.GENERIC.Web.Core.Services.Implementation.Project;
using PTSL.GENERIC.Web.Core.Services.Interface.Project;
using PTSL.GENERIC.Web.Helper;
using static iText.IO.Util.IntHashtable;

namespace PTSL.GENERIC.Web.Controllers.GeneralSetup
{
    [SessionAuthorize]
    public class BugAndDefectController : Controller
    {
        private readonly IBugAndDefectService _BugAndDefectService;
        private readonly IProjectRequestService _ProjectRequestService;
        private readonly ITaskService _TaskService;
        private readonly ITestCaseService _TestCaseService;
        private readonly FileHelper _fileHelper;
        private IProjectStateLogService _projectStateLogService;

        public BugAndDefectController(HttpHelper httpHelper, FileHelper fileHelper)
        {
            _BugAndDefectService = new BugAndDefectService(httpHelper);
            _ProjectRequestService = new ProjectRequestService(httpHelper);
            _TaskService = new TaskService(httpHelper);
            _TestCaseService = new TestCaseService(httpHelper);
            _fileHelper = fileHelper;
            _projectStateLogService = new ProjectStateLogService(httpHelper);
        }
        // GET: BugAndDefect
        public async Task<ActionResult> Index()
        {
            (ExecutionState executionState, IList<ProjectRequestVM> entity, string message) returnResponseProject = await _ProjectRequestService.GetProjectAcceptedList();
            if (returnResponseProject.entity != null)
            {
                var filterdUser = returnResponseProject.entity.ToList();
                ViewBag.ProjectRequestId = new SelectList(filterdUser ?? new List<ProjectRequestVM>(), "Id", "ProjectName");
                ViewBag.ApprovedProjectId = new SelectList(filterdUser ?? new List<ProjectRequestVM>(), "Id", "ProjectName");
            }
            else
            {
                ViewBag.ProjectRequestId = new SelectList("");
                ViewBag.ApprovedProjectId = new SelectList("");
            }
            (ExecutionState executionState, List<TaskVM> entity, string message) returnResponseTask = await _TaskService.List();
            if (returnResponseTask.entity != null)
            {
                var filterdUser = returnResponseTask.entity.ToList();
                ViewBag.TaskOfProjectId = new SelectList(filterdUser ?? new List<TaskVM>(), "Id", "TaskTitle");
            }
            else
            {
                ViewBag.TaskOfProjectId = new SelectList("");
            }
            (ExecutionState executionState, List<TestCaseVM> entity, string message) returnResponseTestCase = _TestCaseService.List();
            if (returnResponseTestCase.entity != null)
            {
                var filterdUser = returnResponseTestCase.entity.ToList();
                ViewBag.TestCaseId = new SelectList(filterdUser ?? new List<TestCaseVM>(), "Id", "TestCaseNo");
            }
            else
            {
                ViewBag.TestCaseId = new SelectList("");
            }
            ViewBag.BugAndDefectSeverity = new SelectList(EnumHelper.GetEnumDropdowns<BugAndDefectSeverity>(), "Id", "Name");
            ViewBag.BugAndDefectStatus = new SelectList(EnumHelper.GetEnumDropdowns<BugAndDefectStatus>(), "Id", "Name");
            (ExecutionState executionState, List<BugAndDefectVM> entity, string message) returnResponse = _BugAndDefectService.List();
            return View(returnResponse.entity);
        }

        // GET: BugAndDefect/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            (ExecutionState executionState, BugAndDefectVM entity, string message) returnResponse = _BugAndDefectService.GetById(id);
            return View(returnResponse.entity);
        }

        // GET: BugAndDefect/Create
        public async Task<ActionResult> Create()
        {
            (ExecutionState executionState, IList<ProjectRequestVM> entity, string message) returnResponseProject = await _ProjectRequestService.GetProjectAcceptedList();
            if (returnResponseProject.entity != null)
            {
                var filterdUser = returnResponseProject.entity.ToList();
                ViewBag.ProjectRequestId = new SelectList(filterdUser ?? new List<ProjectRequestVM>(), "Id", "ProjectName");
            }
            else
            {
                ViewBag.ProjectRequestId = new SelectList("");
            }
            ViewBag.TaskOfProjectId = new SelectList("");
            ViewBag.TestCaseId = new SelectList("");
            ViewBag.BugAndDefectSeverity = new SelectList(EnumHelper.GetEnumDropdowns<BugAndDefectSeverity>(), "Id", "Name");
            ViewBag.BugAndDefectStatus = new SelectList(EnumHelper.GetEnumDropdowns<BugAndDefectStatus>(), "Id", "Name");
            BugAndDefectVM entity = new BugAndDefectVM();
            return View(entity);
        }

        // POST: BugAndDefect/Create
        [HttpPost]
        public ActionResult Create(BugAndDefectVM entity)
        {
            try
            {

                entity.IsActive = true;
                entity.CreatedAt = DateTime.Now;
                var documentFiles = HttpContext.Request.Form.Files.GetFiles("BugAndDefectFiles");
                if (SaveFiles(documentFiles, ref entity, FileType.Document, out var documentFileError) == false)
                {
                    return Json(
                        new { Success = false, Message = documentFileError },
                        SerializerOption.Default);
                }
                (ExecutionState executionState, BugAndDefectVM entity, string message) returnResponse = _BugAndDefectService.Create(entity);


                if (returnResponse.executionState.ToString() != "Created")
                {
                    return View(entity);
                }
                else
                {
                    long EnumId = (long)ProjectState.TestingInProgress;
                    var logres = _projectStateLogService.GetLogData(returnResponse.entity.ProjectRequestId, EnumId);
                    if (logres.entity == null)
                    {
                        ProjectStateLogVM projectStateLog = new ProjectStateLogVM
                        {
                            ProjectRequestId = returnResponse.entity.ProjectRequestId,
                            ProjectState = ProjectState.TestingInProgress,
                            IsStateCompleted = true
                        };
                        var ProjectStateResult = _projectStateLogService.Create(projectStateLog);
                    }
                    return RedirectToAction("Index");
                }

            }
            catch
            {
                return View(entity);
            }
        }


        // GET: BugAndDefect/Edit/5
        public async Task <ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            (ExecutionState executionState, BugAndDefectVM entity, string message) returnResponse = _BugAndDefectService.GetById(id);
            ViewBag.BugAndDefectSeverity = new SelectList(EnumHelper.GetEnumDropdowns<BugAndDefectSeverity>(), "Id", "Name", (int)returnResponse.entity.BugAndDefectSeverity);
            ViewBag.BugAndDefectStatus = new SelectList(EnumHelper.GetEnumDropdowns<BugAndDefectStatus>(), "Id", "Name", (int)returnResponse.entity.BugAndDefectStatus);
            (ExecutionState executionState, IList<ProjectRequestVM> entity, string message) returnResponseProject = await _ProjectRequestService.GetProjectAcceptedList();
            if (returnResponseProject.entity != null)
            {
                var filterdUser = returnResponseProject.entity.ToList();
                ViewBag.ProjectRequestId = new SelectList(filterdUser ?? new List<ProjectRequestVM>(), "Id", "ProjectName", returnResponse.entity.ProjectRequestId);
            }
            else
            {
                ViewBag.ProjectRequestId = new SelectList("");
            }


            (ExecutionState executionState, List<TaskVM> entity, string message) returnResponseTask = await _TaskService.List();
            if (returnResponseProject.entity != null)
            {
                var filterdUser = returnResponseTask.entity.ToList();
                ViewBag.TaskOfProjectId = new SelectList(filterdUser ?? new List<TaskVM>(), "Id", "TaskTitle", returnResponse.entity.TaskOfProjectId);
            }
            else
            {
                ViewBag.TaskOfProjectId = new SelectList("");
            }
            (ExecutionState executionState, List<TestCaseVM> entity, string message) returnResponseTestCase = _TestCaseService.List();
            if (returnResponseProject.entity != null)
            {
                var filterdUser = returnResponseTestCase.entity.ToList();
                ViewBag.TestCaseId = new SelectList(filterdUser ?? new List<TestCaseVM>(), "Id", "TestCaseNo", returnResponse.entity.TestCaseId);
            }
            else
            {
                ViewBag.TestCaseId = new SelectList("");
            }

            return View(returnResponse.entity);
        }

        // POST: BugAndDefect/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, BugAndDefectVM entity)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add update logic here
                    if (id != entity.Id)
                    {

PTSL.GENERIC.Web.Core/Views/BugAndDefect/Details.cshtml
@model PTSL.GENERIC.Web.Core.Model.EntityViewModels.Project.BugAndDefectVM
@using PTSL.GENERIC.Web.Core.Helper.Enum;
@{
    ViewBag.Title = "Details";
    ViewBag.activeMenu = "Bugs and Defects";
}
<style>
    fieldset {
        padding: 0px 15px;
        border: 1px solid gray;
    }

        fieldset legend {
            width: auto;
        }
</style>
<style>
    input, select {
        height: 30px !important;
        line-height: 10px !important;
        font-weight: 400 !important;
        color: black !important;
    }

    legend {
        font-weight: 500 !important;
        font-size: 20px !important;
    }
</style>
<div class="card">
    <div class="card-header">
        <h4>
            <a href="/BugAndDefect/Index" class="mr-1 back">
                <svg width="20" height="20" viewBox="0 0 32 32">
                    <path fill="currentColor" d="m14 26l1.41-1.41L7.83 17H28v-2H7.83l7.58-7.59L14 6L4 16l10 10z" />
                </svg>
            </a>
            Bug and Defect Details
        </h4>
    </div>
    <div class="card-body">
        <div class="card-body">
            <div class="card-body mt-2 gray-card">
                <fieldset class="mb-4">
                    <legend><b>Bug and Defect Information</b></legend>
                    <div class="row">
                        @*
                        <div class="col-md-12" style="padding-bottom:15px">
                        *@
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Project: <b>@Model?.ProjectRequest?.ProjectName</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Task: <b>@Model?.TaskOfProject?.TaskTitle</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Test Case: <b>@Model?.TestCase?.TestCaseName</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Bugzilla Id: <b>@Model?.BugzillaId</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Bug And Defect Severity: <b>@Model?.BugAndDefectSeverity</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Bug And Defect Status: <b>@Model?.BugAndDefectStatus</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">ExpectedResult: <b>@Model?.ExpectedResult</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">ActualResult: <b>@Model?.ActualResult</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Resulation: <b>@Model.Resulation</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Defected Summary: <b>@Model.DefectedSummary</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Steps To Reproduce: <b>@Model.StepstoReproduce</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Reported Date: <b>@Model.ReportedDate</b></label>
                        </div>
                        <div class="form-group col-md-4">
                            <label style="font-size:15px;">Files: </b></label>
                            @foreach (var item in Model.BugAndDefectFiles)
                            {
                                <a class="d-block" target="_blank" href="@item.FileNameUrl">Download Now</a>

                            }
                        </div>
                        @*
                        </div>
                        *@
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
</div>

PTSL.GENERIC.Web.Core/Views/BugAndDefect/Edit.cshtml
@using PTSL.GENERIC.Web.Core.Helper.Enum
@using PTSL.GENERIC.Web.Core.Helper.Enum.Project
@model PTSL.GENERIC.Web.Core.Model.EntityViewModels.Project.BugAndDefectVM
@{
    ViewBag.Title = "Edit";
    ViewBag.activeMenu = "Bugs and Defects";
}
@*<style>
    input, select {
        height: 30px!important;
        line-height: 10px !important;
        font-weight: 400 !important;
        color: black !important;
    }
    legend {
        font-weight: 500 !important;
        font-size: 20px!important;
    }
</style>*@



<div class="card">
    <div class="card-header">
        <h4>
            <a href="/BugAndDefect/Index" class="mr-1 back">
                <svg width="20" height="20" viewBox="0 0 32 32">
                    <path fill="currentColor" d="m14 26l1.41-1.41L7.83 17H28v-2H7.83l7.58-7.59L14 6L4 16l10 10z" />
                </svg>
            </a>
            Bug And Defect
        </h4>
        @* <button class="ml-auto reset btn btn-sm" onclick="resetFromData('#Test StepForm')">
            <svg class="rotate180z" width="16" height="16" viewBox="0 0 32 32">
                <path d="M25.95 7.65l.005-.004c-.092-.11-.197-.206-.293-.312c-.184-.205-.367-.41-.563-.603c-.139-.136-.286-.262-.43-.391c-.183-.165-.366-.329-.558-.482c-.16-.128-.325-.247-.49-.367c-.192-.14-.385-.277-.585-.406a13.513 13.513 0 0 0-.533-.324q-.308-.179-.625-.341c-.184-.094-.37-.185-.56-.27c-.222-.1-.449-.191-.678-.28c-.19-.072-.378-.145-.571-.208c-.246-.082-.498-.15-.75-.217c-.186-.049-.368-.102-.556-.143c-.29-.063-.587-.107-.883-.15c-.16-.023-.315-.056-.476-.073A12.933 12.933 0 0 0 6 7.703V4H4v8h8v-2H6.811A10.961 10.961 0 0 1 16 5a11.111 11.111 0 0 1 1.189.067c.136.015.268.042.403.061c.25.037.501.075.746.128c.16.035.315.08.472.121c.213.057.425.114.633.183c.164.054.325.116.486.178c.193.074.384.15.57.235c.162.072.32.15.477.23q.268.136.526.286c.153.09.305.18.453.276c.168.11.33.224.492.342c.14.102.282.203.417.312c.162.13.316.268.47.406c.123.11.248.217.365.332c.167.164.323.338.479.512A10.993 10.993 0 1 1 5 16H3a13 13 0 1 0 22.95-8.35z" fill="currentColor" />
            </svg>
            Reset
        </button> *@
    </div>

    <div class="card-body">
        @using (Html.BeginForm("Edit", "BugAndDefect", FormMethod.Post, new { id = "Test StepForm" }))
        {
            <input type="hidden" name="Id" id="Id" value="@Model.Id" />
            <input type="hidden" name="ProjectRequestId" id="ProjectRequestId" value="@Model.ProjectRequestId" />
            <input type="hidden" name="TaskOfProjectId" id="TaskOfProjectId" value="@Model.TaskOfProjectId" />
            <input type="hidden" name="ReportedBy" id="ReportedBy" value="@Model.ReportedBy" />
            <input type="hidden" name="TestCaseId" id="TestCaseId" value="@Model.TestCaseId" />
            <input type="hidden" name="CreatedBy" id="CreatedBy" value="@Model.CreatedBy" />
            <input type="hidden" name="CreatedAt" id="CreatedAt" value="@Model.CreatedAt" />
            <input type="hidden" name="BugzillaId" id="BugzillaId" value="@Model.BugzillaId" />
            <input type="hidden" name="DefectId" id="DefectId" value="@Model.DefectId" />
            <div class="col-12 p-1 card-body mt-2 gray-card">
                
                <fieldset class="p-2">
                    <legend class="float-none w-auto">Bug And Defect Details</legend>
                    <div class="row custom">
                        <div class="col-6 p-1">
                            <label class="m-0">Project <span style="color: red;">*</span></label>
                            @Html.DropDownList("ProjectRequestId", null, "Choose Project", htmlAttributes: new { @class = "form-control col-md-12", @disabled = "disabled" })
                        </div>
                        <div class="col-6 p-1">
                            <label class="m-0">Task <span style="color: red;">*</span></label>
                            @Html.DropDownList("TaskOfProjectId", null, "Choose Task", htmlAttributes: new { @class = "form-control col-md-12", @disabled = "disabled" })
                        </div>
                        <div class="col-6 p-1">
                            <label class="m-0">Test Case <span style="color: red;">*</span></label>
                            @Html.DropDownList("TestCaseId", null, "Choose Test Case", htmlAttributes: new { @class = "form-control col-md-12", @disabled = "disabled" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 p-1 " style="max-width: 245px;">
                            <label class="m-0">Bug And Defect Severity<span style="color: red;">*</span></label>
                            @Html.DropDownList("BugAndDefectSeverity", null, "Choose BugAndDefectSeverity", htmlAttributes: new { @class = "form-control col-md-12", @required = "required" })
                        </div>
                        <div class="col-6 pr-1" style="max-width: 245px;">
                            <label class="m-0">Expected Result<span style="color: red;">*</span></label>
                            <input type="text" class="form-control col-md-12" id="ExpectedResult" name="ExpectedResult" value="@Model.ExpectedResult" placeholder="Enter Expected Result" required>
                        </div>
                        <div class="col-6 pr-1" style="max-width: 245px;">
                            <label class="m-0">ActualResult<span style="color: red;">*</span></label>
                            <input type="text" class="form-control col-md-12" id="ActualResult" name="ActualResult" value="@Model.ActualResult" placeholder="Enter Actual Result" required>
                        </div>

                        <div class="col-6 pr-1" style="max-width: 245px;">
                            <label class="m-0">Resulation <span style="color: red;">*</span></label>
                            <input type="text" class="form-control col-md-12" id="Resulation" name="Resulation" value="@Model.Resulation" placeholder="Enter Resulation" required>
                        </div>
                        <div class="col-6 p-1" style="max-width: 245px;">
                            <label class="m-0">Bug And Defect Status <span style="color: red;">*</span></label>
                            @Html.DropDownList("BugAndDefectStatus", null, "choose Bug And Defect Status", htmlAttributes: new { @class = "form-control col-md-12" })
                        </div>
                        <div class="col-6 pr-1" style="max-width: 245px;">
                            <label class="m-0">Defected Summary <span style="color: red;">*</span></label>
                            <textarea type="text" class="form-control col-md-12" id="DefectedSummary" name="DefectedSummary" value="@Model.DefectedSummary" placeholder="Enter Defected Summary">@Model.DefectedSummary</textarea>
                        </div>
                        <div class="col-6 pr-1" style="max-width: 245px;">
                            <label class="m-0">Steps to Reproduce <span style="color: red;">*</span></label>
                            <input type="text" class="form-control col-md-12" id="StepstoReproduce" name="StepstoReproduce" value="@Model.StepstoReproduce" placeholder="Enter Steps to Reproduce" required>
                        </div>
                        <div class="col-6 pr-1" style="max-width: 245px;">
                            <label class="m-0">Reported Date <span style="color: red;">*</span></label>
                            <input type="date" class="form-control col-md-12" id="ReportedDate" name="ReportedDate" value="@Model.ReportedDate?.ToString("yyyy-MM-dd")" placeholder="Enter Reported Date" required>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-primary submit-btn pull-right btn-sm">Submit</button>
                    </div>
                </fieldset>
            </div>
        }
    </div>
    <hr />
    <div class="card-header pull-left">
       <!--<a href="/Test Step/Index" class="btn btn-warning">Return to Index</a>-->
    </div>
</div>

<script>
    $(".submit-btn").on("click", function () {
        if ($("#Test StepForm").valid()) {
            //Do something here
            $(".loader").fadeIn("slow");
        }
    });

    $("#Test StepForm").validate({
        // Specify validation rules
        rules: {
            Test StepName: "required"
        },

    });
</script>