PTSL.GENERIC.Web.Core/Controllers/Project/AgreementDocumentController.cs
using iText.Html2pdf;
using iText.Kernel.Pdf;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PTSL.eCommerce.Web.Core.Services.Interface.Project;
using PTSL.GENERIC.Web.Core.Enum.Documents;
using PTSL.GENERIC.Web.Core.Helper;
using PTSL.GENERIC.Web.Core.Helper.Enum;
using PTSL.GENERIC.Web.Core.Helper.Enum.Documents;
using PTSL.GENERIC.Web.Core.Helper.Enum.PermissionSettings;
using PTSL.GENERIC.Web.Core.Model;
using PTSL.GENERIC.Web.Core.Model.EntityViewModels;
using PTSL.GENERIC.Web.Core.Model.EntityViewModels.Documents;
using PTSL.GENERIC.Web.Core.Model.EntityViewModels.Project;
using PTSL.GENERIC.Web.Core.Services.Implementation.Documents;
using PTSL.GENERIC.Web.Core.Services.Implementation.GeneralSetup;
using PTSL.GENERIC.Web.Core.Services.Implementation.PermissionSettings;
using PTSL.GENERIC.Web.Core.Services.Implementation.Project;
using PTSL.GENERIC.Web.Core.Services.Implementation.SystemUser;
using PTSL.GENERIC.Web.Core.Services.Interface.Documents;
using PTSL.GENERIC.Web.Core.Services.Interface.PermissionSettings;
using PTSL.GENERIC.Web.Core.Services.Interface.Project;
using PTSL.GENERIC.Web.Core.Services.Interface.SystemUser;
using PTSL.GENERIC.Web.Helper;
using static iText.IO.Util.IntHashtable;
using static iText.StyledXmlParser.Jsoup.Select.Evaluator;
using DocumentApprovalStatus = PTSL.GENERIC.Web.Core.Helper.Enum.DocumentApprovalStatus;
using DocumentType = PTSL.GENERIC.Web.Core.Enum.Documents.DocumentType;

namespace PTSL.GENERIC.Web.Controllers.GeneralSetup
{
    [SessionAuthorize]
    public class AgreementDocumentController : Controller
    {
        private readonly IAgreementDocumentService _AgreementDocumentService;
        private readonly IProjectRequestService _ProjectRequestService;
        private readonly IAllTypesDocumentService _AllTypesDocumentService;
        private readonly IUserRoleService _UserRoleService;
        private readonly IUserService _UserService;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IPermissionHeaderSettingsService _permissionHeaderSettingsService;
        private readonly IApprovalForAllDocumentService _ApprovalForAllDocumentService;
        private readonly IDefaultDocContentService _DefaultDocContentService;
        public AgreementDocumentController(HttpHelper httpHelper, IWebHostEnvironment hostEnvironment)
        {
            _AgreementDocumentService = new AgreementDocumentService(httpHelper);
            _AllTypesDocumentService = new AllTypesDocumentService(httpHelper);
            _ApprovalForAllDocumentService = new ApprovalForAllDocumentService(httpHelper);
            _ProjectRequestService = new ProjectRequestService(httpHelper);
            _UserRoleService = new UserRoleService(httpHelper);
            _UserService = new UserService(httpHelper);
            _hostEnvironment = hostEnvironment;
            _permissionHeaderSettingsService = new PermissionHeaderSettingsService(httpHelper);
            _DefaultDocContentService = new DefaultDocContentService(httpHelper);
        }
        // GET: AgreementDocument
        public async Task<ActionResult> Index()
        {
            (ExecutionState executionState, List<AllTypesOfDocumentVM> entity, string message) returnResponse = await _AllTypesDocumentService.List();

            List<AllTypesOfDocumentVM> entityList = new List<AllTypesOfDocumentVM>();
            var allDocumentApprovalLog = await _ApprovalForAllDocumentService.List();
            var filteredApprovalLog = allDocumentApprovalLog.entity ?? new List<ApprovalForAllDocumentVM>();
            entityList = returnResponse.entity is not null ? returnResponse.entity.Where(s=>s.DocumentType == DocumentType.Agreement).Select(x => new AllTypesOfDocumentVM()
            {
                Id = x.Id,
                ProjectRequest = x.ProjectRequest,
                ProjectRequestId = x.ProjectRequestId,
                DocumentType = x.DocumentType,
                TestingType = x.TestingType,
                VersionNo = x.VersionNo,
                EditorContent = x.EditorContent,
                CreatedAt = ConvertUTCToBdTime(x.CreatedAt),
                FileName = x.FileName,
                FilePath = x.FilePath,
                ViewVersionNo = x.ViewVersionNo,
                DocumentApprovalStatus = x.DocumentApprovalStatus,
                DocumentAmendmentState = x.DocumentAmendmentState,
                HasEditAndDltPrmsn = filteredApprovalLog.Where(s => s.AllTypesOfDocumentId == x.Id).Any() ? false : true,
            }).OrderByDescending(s => s.Id).ToList() : new List<AllTypesOfDocumentVM>();
            return View(entityList);
        }

        public async Task<IActionResult> PendingAgreementDocs()
        {
            (ExecutionState executionState, List<AllTypesOfDocumentVM> entity, string message) returnResponse = await _AllTypesDocumentService.List();

            List<AllTypesOfDocumentVM> entityList = new List<AllTypesOfDocumentVM>();

            var userRoleId = Convert.ToInt64(HttpContext.Session.GetString(SessionKey.UserRoleId));
            var RoleName = _UserRoleService.GetById(userRoleId).entity?.RoleName;
            var userId = Convert.ToInt64(HttpContext.Session.GetString(SessionKey.UserId));
            var userType = _UserService.GetById(userId).entity?.UserType;
            bool hasEditDeletePermission = false;
            if (userType != 0 && userType != null)
            {
                if (userType == UserType.SQTC_Admin || userType == UserType.SQTC_User)
                {
                    ViewBag.HasCreatePermission = true;
                    hasEditDeletePermission = true;
                }
                else
                {
                    ViewBag.HasCreatePermission = false;
                    hasEditDeletePermission = false;
                }
            }
            else
            {
                ViewBag.HasCreatePermission = false;
                hasEditDeletePermission = false;
            }

            var allDocumentApprovalLog = await _ApprovalForAllDocumentService.List();
            var filteredApprovalLog = allDocumentApprovalLog.entity ?? new List<ApprovalForAllDocumentVM>();

            if (filteredApprovalLog.Any())
            {
                long moduleEnumId = (long)ModuleEnum.AgreementApproval;

                var roleResult = _permissionHeaderSettingsService.GetPermissionHeaderSettingsByModuleEnumId(moduleEnumId)
                .entity.FirstOrDefault();
                var NewResultRoleId = roleResult?.PermissionRowSettings?.LastOrDefault()?.UserRoleId;
                foreach (var item in returnResponse.entity.Where(x => x.DocumentApprovalStatus == DocumentApprovalStatus.Pending && x.DocumentType == DocumentType.Agreement))
                {
                    var findCurrDocApprovalLog = filteredApprovalLog.Where(x => x.AllTypesOfDocumentId == item.Id).LastOrDefault();
                    hasEditDeletePermission = filteredApprovalLog.Where(x => x.AllTypesOfDocumentId == item.Id).Any() ? false : true;
                    //var userId = Convert.ToInt64(HttpContext.Session.GetString(SessionKey.UserId));
                    var CurrentUserRoleId = Convert.ToInt64(HttpContext.Session.GetString(SessionKey.UserRoleId));

                    if (findCurrDocApprovalLog != null && findCurrDocApprovalLog.ReceiverId == userId && CurrentUserRoleId != NewResultRoleId)
                        item.IsApprovalShow = true;
                    else if (item.DocumentAmendmentState == DocumentAmendmentState.Amendmented)
                    {
                        if (findCurrDocApprovalLog is not null && findCurrDocApprovalLog?.IsAmmendment == true && findCurrDocApprovalLog.ReceiverId == userId &&
                            CurrentUserRoleId == NewResultRoleId)
                        {
                            item.IsApprovalShow = false;
                            item.IsAcceptOrReject = true;
                        }
                        else if (findCurrDocApprovalLog?.ReceiverId is null)
                            item.IsApprovalShow = true;
                        else if (findCurrDocApprovalLog.ReceiverId == userId && CurrentUserRoleId == NewResultRoleId)
                            item.IsApprovalShow = true;
                        else
                            item.IsApprovalShow = false;
                    }
                    else if(item.DocumentAmendmentState == DocumentAmendmentState.Amendmented && findCurrDocApprovalLog?.ReceiverId is null)
                        item.IsApprovalShow = true;
                    else if (findCurrDocApprovalLog != null && findCurrDocApprovalLog.ReceiverId == userId && CurrentUserRoleId == NewResultRoleId)
                    {
                        item.IsApprovalShow = false;
                        item.IsAcceptOrReject = true;
                    }
                    else if (findCurrDocApprovalLog == null)
                        item.IsApprovalShow = true;
                   
                    item.HasEditAndDltPrmsn = hasEditDeletePermission;
                    item.ApprovalMessage = findCurrDocApprovalLog?.Description;

                }
            }
            else
            {
                if (returnResponse.entity != null)
                {
                    foreach (var item in returnResponse.entity.Where(x => x?.DocumentApprovalStatus == DocumentApprovalStatus.Pending && x?.DocumentType == DocumentType.Agreement) ?? new List<AllTypesOfDocumentVM>())
                    {
                        item.IsApprovalShow = true;
                        item.HasEditAndDltPrmsn = true;
                    }
                }
  
            }


            ViewBag.ProjectType = new SelectList(EnumHelper.GetEnumDropdowns<ProjectType>(), "Id", "Name");

PTSL.GENERIC.Web.Core/Views/AgreementDocument/AmendmentedList.cshtml
@model IEnumerable<PTSL.GENERIC.Web.Core.Model.EntityViewModels.Documents.AllTypesOfDocumentVM>
@{
    ViewBag.Title = "Index";
    ViewBag.activeMenu = "Amendmented Agreement Documents";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="col-md-10">
                    <h4>Amendmented Agreement Documents</h4>
                </div>
                @*  <div class="col-md-2 text-right">
                <a href="/AllTypesDocument/Create" class="badge badge-success badge-shadow">Create New</a>
                </div> *@
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="tableExport_filter" style="width:100%;">
                        <thead>
                            <tr>
                                <th>SL</th>
                                <th>Project</th>
                                <th>Document Type</th>
                                <th>Testing Type</th>
                                <th>Version No</th>
                                <th>Approval Status</th>
                                <th>Created Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        @{
                            int i = 1;
                        }
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var data in Model)
                                {
                                    <tr>
                                        <td>@i</td>
                                        <td>@data.ProjectRequest?.ProjectName</td>
                                        <td>@data.DocumentType</td>
                                        <td>@data.TestingType</td>
                                        <td>@data.ViewVersionNo</td>
                                        <td>@data.DocumentApprovalStatus</td>
                                        <td>
                                            @data.CreatedAt.ToString("dd/MMM/yyyy hh:mm:ss")
                                        </td>
                                        <td>
                                            <a class="btn btn-icon" href="/AllTypesDocument/AmendmentDetails/@data.Id" target="_blank" title="View Amendment Details"><img src="~/img/view.png" /></a>
                                            <a href="@data.FilePath" class="btn btn-info" target="_blank"><i class="fa fa-file" title="View Document"></i></a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#tableExport_filter').DataTable({
            pageLength: 5
        });
    });

    // function showDeleteConfirmMessage(id) {
    //     swal({
    //         title: "Are you sure?",
    //         text: "You will not be able to recover this imaginary file!",
    //         type: "warning",
    //         showCancelButton: true,
    //         confirmButtonColor: "#DD6B55",
    //         confirmButtonText: "Yes, delete it!",
    //         closeOnConfirm: false
    //     }, function () {
    //         var data = { 'id': id };
    //         $.ajax({
    //             type: "GET",
    //             contentType: "application/json; charset=utf-8",
    //             url: "/AgreementDocument/Delete",
    //             data: data,
    //             datatype: "json",
    //             success: function (result) {
    //                 console.log(result);
    //                 var message = result.Message;
    //                 var executionState = result.executionState;
    //                 if (executionState != null) {
    //                     swal("Deleted!", "Your imaginary file has been deleted.", "success");
    //                     $(".confirm").on('click', function () {
    //                         window.location.reload();
    //                     });
    //                 }
    //             },
    //             error: function (xmlhttprequest, textstatus, errorthrown) {
    //                 swal("Not Deleted!", "Your imaginary file has not been deleted.", "error");
    //             }
    //         });
    //     });
    // }
</script>

PTSL.GENERIC.Web.Core/Views/AgreementDocument/AmendmentedListForClient.cshtml
@model IEnumerable<PTSL.GENERIC.Web.Core.Model.EntityViewModels.Documents.AllTypesOfDocumentVM>
@{
    ViewBag.Title = "Index";
    ViewBag.activeMenu = "Amendmented Agreement Documents";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="col-md-10">
                    <h4>Amendmented Agreement Documents</h4>
                </div>
                @*  <div class="col-md-2 text-right">
                <a href="/AllTypesDocument/Create" class="badge badge-success badge-shadow">Create New</a>
                </div> *@
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="tableExport_filter" style="width:100%;">
                        <thead>
                            <tr>
                                <th>SL</th>
                                <th>Project</th>
                                <th>Document Type</th>
                                <th>Testing Type</th>
                                <th>Version No</th>
                                <th>Approval Status</th>
                                <th>Created Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        @{
                            int i = 1;
                        }
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var data in Model)
                                {
                                    <tr>
                                        <td>@i</td>
                                        <td>@data.ProjectRequest?.ProjectName</td>
                                        <td>@data.DocumentType</td>
                                        <td>@data.TestingType</td>
                                        <td>@data.ViewVersionNo</td>
                                        <td>@data.DocumentApprovalStatus</td>
                                        <td>
                                            @data.CreatedAt.ToString("dd/MMM/yyyy hh:mm:ss")
                                        </td>
                                        <td>
                                            <a class="btn btn-icon" href="/AllTypesDocument/AmendmentDetails/@data.Id" target="_blank" title="View Amendment Details"><img src="~/img/view.png" /></a>
                                            <a href="@data.FilePath" class="btn btn-info" target="_blank"><i class="fa fa-file" title="View Document"></i></a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#tableExport_filter').DataTable({
            pageLength: 5
        });
    });

    // function showDeleteConfirmMessage(id) {
    //     swal({
    //         title: "Are you sure?",
    //         text: "You will not be able to recover this imaginary file!",
    //         type: "warning",
    //         showCancelButton: true,
    //         confirmButtonColor: "#DD6B55",
    //         confirmButtonText: "Yes, delete it!",
    //         closeOnConfirm: false
    //     }, function () {
    //         var data = { 'id': id };
    //         $.ajax({
    //             type: "GET",
    //             contentType: "application/json; charset=utf-8",
    //             url: "/AgreementDocument/Delete",
    //             data: data,
    //             datatype: "json",
    //             success: function (result) {
    //                 console.log(result);
    //                 var message = result.Message;
    //                 var executionState = result.executionState;
    //                 if (executionState != null) {
    //                     swal("Deleted!", "Your imaginary file has been deleted.", "success");
    //                     $(".confirm").on('click', function () {
    //                         window.location.reload();
    //                     });
    //                 }
    //             },
    //             error: function (xmlhttprequest, textstatus, errorthrown) {
    //                 swal("Not Deleted!", "Your imaginary file has not been deleted.", "error");
    //             }
    //         });
    //     });
    // }
</script>

PTSL.GENERIC.Web.Core/Views/AgreementDocument/ApprovedList.cshtml
@model IEnumerable<PTSL.GENERIC.Web.Core.Model.EntityViewModels.Documents.AllTypesOfDocumentVM>
@{
    ViewBag.Title = "Index";
    ViewBag.activeMenu = "Approved Agreement Documents";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="col-md-10">
                    <h4>Approved Agreement Documents</h4>
                </div>
                @*  <div class="col-md-2 text-right">
                <a href="/AllTypesDocument/Create" class="badge badge-success badge-shadow">Create New</a>
                </div> *@
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="tableExport_filter" style="width:100%;">
                        <thead>
                            <tr>
                                <th>SL</th>
                                <th>Project</th>
                                <th>Document Type</th>
                                <th>Testing Type</th>
                                <th>Version No</th>
                                <th>Created Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        @{
                            int i = 1;
                        }
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var data in Model)
                                {
                                    <tr>
                                        <td>@i</td>
                                        <td>@data.ProjectRequest?.ProjectName</td>
                                        <td>@data.DocumentType</td>
                                        <td>@data.TestingType</td>
                                        <td>@data.ViewVersionNo</td>
                                        <td>
                                            @data.CreatedAt.ToString("dd/MMM/yyyy hh:mm:ss")
                                        </td>
                                        <td>
                                            @*  <a class="btn btn-primary" href="/AllTypesDocument/Edit/@data.Id"><i class="fa fa-edit" title="Edit Document"></i></a> *@
                                            <a href="@data.FilePath" class="btn btn-icon" target="_blank" title="View File"><img src="~/img/view.png" /></a>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#tableExport_filter').DataTable({
            pageLength: 5
        });
    });

    function showDeleteConfirmMessage(id) {
        swal({
            title: "Are you sure?",
            text: "You will not be able to recover this imaginary file!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            closeOnConfirm: false
        }, function () {
            var data = { 'id': id };
            $.ajax({
                type: "GET",
                contentType: "application/json; charset=utf-8",
                url: "/AgreementDocument/Delete",
                data: data,
                datatype: "json",
                success: function (result) {
                    console.log(result);
                    var message = result.Message;
                    var executionState = result.executionState;
                    if (executionState != null) {
                        swal("Deleted!", "Your imaginary file has been deleted.", "success");
                        $(".confirm").on('click', function () {
                            window.location.reload();
                        });
                    }
                },
                error: function (xmlhttprequest, textstatus, errorthrown) {
                    swal("Not Deleted!", "Your imaginary file has not been deleted.", "error");
                }
            });
        });
    }
</script>

PTSL.GENERIC.Web.Core/Views/AgreementDocument/CreateDoc.cshtml
@model PTSL.GENERIC.Web.Core.Model.EntityViewModels.Project.AgreementDocumentsVM
@{
    ViewBag.Title = "Create";
    var Message = ViewBag.Message;
}
@*<style>
    input, select {
        height: 30px !important;
        line-height: 10px !important;
        font-weight: 400 !important;
        color: black !important;
    }

    legend {
        font-weight: 500 !important;
        font-size: 20px !important;
    }
</style>*@


<div class="card">
    <link href="~/SummerNote/summernote.min.css" rel="stylesheet">
    <div class="card-header">
        <h4>
            <a href="/AgreementDocument/Index" class="mr-1 back">
                <svg width="20" height="20" viewBox="0 0 32 32">
                    <path fill="currentColor" d="m14 26l1.41-1.41L7.83 17H28v-2H7.83l7.58-7.59L14 6L4 16l10 10z" />
                </svg>
            </a>
            Create New Agreement Document
        </h4>
        <button class="ml-auto reset btn btn-sm" onclick="resetFromData('#AgreementDocumentForm')">
            <svg class="rotate180z" width="16" height="16" viewBox="0 0 32 32">
                <path d="M25.95 7.65l.005-.004c-.092-.11-.197-.206-.293-.312c-.184-.205-.367-.41-.563-.603c-.139-.136-.286-.262-.43-.391c-.183-.165-.366-.329-.558-.482c-.16-.128-.325-.247-.49-.367c-.192-.14-.385-.277-.585-.406a13.513 13.513 0 0 0-.533-.324q-.308-.179-.625-.341c-.184-.094-.37-.185-.56-.27c-.222-.1-.449-.191-.678-.28c-.19-.072-.378-.145-.571-.208c-.246-.082-.498-.15-.75-.217c-.186-.049-.368-.102-.556-.143c-.29-.063-.587-.107-.883-.15c-.16-.023-.315-.056-.476-.073A12.933 12.933 0 0 0 6 7.703V4H4v8h8v-2H6.811A10.961 10.961 0 0 1 16 5a11.111 11.111 0 0 1 1.189.067c.136.015.268.042.403.061c.25.037.501.075.746.128c.16.035.315.08.472.121c.213.057.425.114.633.183c.164.054.325.116.486.178c.193.074.384.15.57.235c.162.072.32.15.477.23q.268.136.526.286c.153.09.305.18.453.276c.168.11.33.224.492.342c.14.102.282.203.417.312c.162.13.316.268.47.406c.123.11.248.217.365.332c.167.164.323.338.479.512A10.993 10.993 0 1 1 5 16H3a13 13 0 1 0 22.95-8.35z" fill="currentColor" />
            </svg>
            Reset
        </button>
    </div>

    

    <div class="card-body">
        @using (Html.BeginForm("CreateDocumentList", "AgreementDocument", FormMethod.Post, new { id = "AgreementDocumentForm" }))
        {
            <div class="form-horizontal">

                <div class="col-md-6">
                    <div class="col-6 p-1">
                        <label class="m-0">Project <span style="color: red;">*</span></label>
                        @Html.DropDownList("ProjectRequestId", null, "Choose Project", htmlAttributes: new { @class = "form-control col-md-12", @required = "required" })
                    </div>

                    @* @for (int number = 0; number < 5; number++)
                { *@
                    <div class="form-group form-float">
                        <label class="form-label" for="termsDescription"><h5>HtmlText_1</h5><span style="color:red">*</span></label>
                        <div class="form-line">
                            <textarea rows="500" id="HtmlText_1" name="Agreement_FirstPage" class="form-control" required> @Model.Agreement_FirstPage</textarea>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <label class="form-label" for="termsDescription"><h5>HtmlText_2</h5><span style="color:red">*</span></label>
                        <div class="form-line">
                            <textarea rows="500" id="HtmlText_2" name="Agreement_SecondPage" class="form-control" required>@Model.Agreement_SecondPage</textarea>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <label class="form-label" for="termsDescription"><h5>HtmlText_3</h5><span style="color:red">*</span></label>
                        <div class="form-line">
                            <textarea rows="500" id="HtmlText_3" name="Agreement_ThirdPage" class="form-control" required>@Model.Agreement_ThirdPage</textarea>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <label class="form-label" for="termsDescription"><h5>HtmlText_4</h5><span style="color:red">*</span></label>
                        <div class="form-line">
                            <textarea rows="500" id="HtmlText_4" name="Agreement_ForthPage" class="form-control" required>@Model.Agreement_ForthPage</textarea>
                        </div>
                    </div>
                    @*  } *@

                </div>

                <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-primary submit-btn pull-right btn-sm">Submit</button>
                </div>
            </div>
        }
    </div>
    <hr />
    <div class="card-header pull-left">
        <!-- <a href="/AgreementDocument/Index" class="btn btn-warning">Return to Index</a> -->
    </div>
</div>
<script src="~/SummerNote/summernote.min.js"></script>
<script>
    $(document).ready(function () {
        for (var num = 0; num < 5; num++) {
            var id = "#HtmlText_" + num.toString();
            $(id).summernote();
        }
    });
</script>